schema = 3

[mod]
  [mod."dario.cat/mergo"]
    version = "v1.0.0"
    hash = "sha256-jlpc8dDj+DmiOU4gEawBu8poJJj9My0s9Mvuk9oS8ww="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20230124172434-306776ec8161"
    hash = "sha256-17hCoOE3HBv6cjpcukfBS6/ULgTuoUZ7RNbi5korH2M="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.2"
    hash = "sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU="
  [mod."github.com/Microsoft/hcsshim"]
    version = "v0.12.3"
    hash = "sha256-Gofu6miKjGZOIwCqubR/Wud5Z46PjbhM7YkkMUFE9bE="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/containerd/containerd"]
    version = "v1.7.16"
    hash = "sha256-AsZx0BdT9lx9eLdHuZNt5wzDr/Pg0FucR3CM1ouNECY="
  [mod."github.com/containerd/log"]
    version = "v0.1.0"
    hash = "sha256-vuE6Mie2gSxiN3jTKTZovjcbdBd1YEExb7IBe3GM+9s="
  [mod."github.com/cpuguy83/dockercfg"]
    version = "v0.3.1"
    hash = "sha256-ILY8MBdfgIZtuSIGEeXFRiVSDAOLAhdGqr9uq0KSiVk="
  [mod."github.com/distribution/reference"]
    version = "v0.6.0"
    hash = "sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4="
  [mod."github.com/docker/docker"]
    version = "v26.1.1+incompatible"
    hash = "sha256-TvemFKPHsM6/ukjuOKhRYFKS9lUZvGGI9OugYqlpdvQ="
  [mod."github.com/docker/go-connections"]
    version = "v0.5.0"
    hash = "sha256-aGbMRrguh98DupIHgcpLkVUZpwycx1noQXbtTl5Sbms="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.1"
    hash = "sha256-WM4badoqxXlBmqCRrnmtNce63dLlr/FJav3BJSYHvaY="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.2"
    hash = "sha256-6fMD2/Rku8HT0zDdeA23pX0YxbohiIOC8OJNYbylJTQ="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.17.1"
    hash = "sha256-KT/7xzUXjvYD4ZwM6IK5RnjMC+d9GjoYu5ZEIn/n4K8="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.8"
    hash = "sha256-8rgCCfHX29le8m6fyVn6gwFde5TPUHjwQqZqv9JIubs="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.7"
    hash = "sha256-bjinp7b7qWk+DcZDDv1EedJxZqGxp2NWY+NYKBfE5xU="
  [mod."github.com/kr/pretty"]
    version = "v0.3.1"
    hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20240408141607-282e7b5d6b74"
    hash = "sha256-mP87o1VlEDpDdEgRrBsAWs79J4AIN8/vyqa2E0FLCvM="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/minio/md5-simd"]
    version = "v1.1.2"
    hash = "sha256-vykcXvy2VBBAXnJott/XsGTT0gk2UL36JzZKfJ1KAUY="
  [mod."github.com/minio/minio-go/v7"]
    version = "v7.0.70"
    hash = "sha256-AK7IEl6r0SGp/KMfiVdM64ggTEyH614+mVjHkGTarwQ="
  [mod."github.com/moby/docker-image-spec"]
    version = "v1.3.1"
    hash = "sha256-xwSNLmMagzywdGJIuhrWl1r7cIWBYCOMNYbuDDT6Jhs="
  [mod."github.com/moby/patternmatcher"]
    version = "v0.6.0"
    hash = "sha256-ny3L8ktj8cyN41CEJhaRT74Vi8HpXXsbTvlrw/Tl5+g="
  [mod."github.com/moby/sys/sequential"]
    version = "v0.5.0"
    hash = "sha256-A29wOMXw/O8L5Kmu3UNb9s9go2Vya8qFEYtsYrg3Rzo="
  [mod."github.com/moby/sys/user"]
    version = "v0.1.0"
    hash = "sha256-ygCkKd2zLnPBrQxcq7nn1vsPx4fsWHiBauhwxK5fpc8="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0"
    hash = "sha256-5OxW1ShHypLpzVu+BJivNlFX2JFPh9WKfJcMIgPZf4U="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20240221224432-82ca36839d55"
    hash = "sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI="
  [mod."github.com/rs/xid"]
    version = "v1.5.0"
    hash = "sha256-u0QLm2YFMJqEjUhpWcLwfoS9lNHUxc2A79MObsqVbVU="
  [mod."github.com/shirou/gopsutil/v3"]
    version = "v3.24.4"
    hash = "sha256-ubkBxu9X4LRhI1HqkjsIShR4e8rQsuKQs4VNOIIhZCU="
  [mod."github.com/shoenig/go-m1cpu"]
    version = "v0.1.6"
    hash = "sha256-hT+JP30BBllsXosK/lo89HV/uxxPLsUyO3dRaDiLnCg="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/tdewolff/minify/v2"]
    version = "v2.20.19"
    hash = "sha256-JAO+JvZM/nV0u/MJLNPAhru02qpz3/EmgsyoEuLYj7s="
  [mod."github.com/tdewolff/parse/v2"]
    version = "v2.7.12"
    hash = "sha256-IOSoNqqQMJ0HNzgas+W6vpSIs4TU1HYjAFBsewzzIbU="
  [mod."github.com/testcontainers/testcontainers-go"]
    version = "v0.30.0"
    hash = "sha256-n4et0MvZzSx6ZoZn3sQfCVLxsmOfKZar3SYumwpjUdU="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.14"
    hash = "sha256-DF4NKSQTv5Z0T89MGqao7GIABcYIazZXTIUHpKIud04="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.8.0"
    hash = "sha256-owNkpN5t3BL8huRO5uMwdAI9qhJxFp9SY6O1oEcWc6k="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.51.0"
    hash = "sha256-CE6tmUrlIQ2DXLV/fe3nS2Andv6QWbUICWrwGN6S2+g="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.26.0"
    hash = "sha256-1LEPxggc0QK1P+Pcht1s8ySMK9eQdR7rQrkiCOtkjHI="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.26.0"
    hash = "sha256-JB3j9ggi6FK+YuKjcSdiVOJ2pnzZ2PdfVIFrpLBPmZs="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.26.0"
    hash = "sha256-n3ZTXu0Ab6RWPDDO4P21mj4dOqDKi4E/35SOHvj5aJE="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."golang.org/x/crypto"]
    version = "v0.22.0"
    hash = "sha256-2+u9nd32+Bi7EEv7QFc12CRTbfV7DApNv+yKIr7+lTw="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240416160154-fe59bbe5cc7f"
    hash = "sha256-168CD9hlLJaQ7stQk/ztlP3zgaWXUMbIHa38gAeRRs4="
  [mod."golang.org/x/image"]
    version = "v0.17.0"
    hash = "sha256-tH5e4+0ero5B5/r5TwzxQZhnfCecQvmoles3UW24X/c="
  [mod."golang.org/x/net"]
    version = "v0.24.0"
    hash = "sha256-w1c21ljta5wNIyel9CSIn/crPzwOCRofNKhqmfs4aEQ="
  [mod."golang.org/x/sys"]
    version = "v0.20.0"
    hash = "sha256-mowlaoG2k4n1c1rApWef5EMiXd3I77CsUi8jPh6pTYA="
  [mod."golang.org/x/text"]
    version = "v0.16.0"
    hash = "sha256-hMTO45upjEuA4sJzGplJT+La2n3oAfHccfYWZuHcH+8="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240311173647-c811ad7063a7"
    hash = "sha256-iDt6IGb38mYmp0oj843HZVyue3pEaMa3T6aD5xZRvrE="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240429193739-8cf5692501f6"
    hash = "sha256-P5SBku16dYnK4koUQxTeGwPxAAWH8rxbDm2pOzFLo/Q="
  [mod."google.golang.org/grpc"]
    version = "v1.63.2"
    hash = "sha256-RmtVjYLam97k7IHTHU7Gn16xNX+GvA9AiLKlQwOiZXU="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.0"
    hash = "sha256-0fqsqQTyOicm4+NiuAf2IaJhavMVJh50VhNcRmZPSus="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
